# Generated by Django 5.2.17 on 2026-09-16 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, help_text='Talaba ID (masalan: 23E-014)', max_length=50, null=True)),
                ('group', models.CharField(default='23E', help_text='Guruh (masalan: 23E)', max_length=50)),
                ('course', models.CharField(default='4', help_text='Bosqich / Kurs (masalan: 4期生 / 4)', max_length=50)),
                ('direction', models.CharField(default='IT', help_text="Yo'nalish (masalan: IT, JAPANESE)", max_length=100)),
                ('avatar_url', models.TextField(blank=True, help_text='Google yoki shaxsiy profil rasmi', null=True)),
                ('is_verified', models.BooleanField(default=True, help_text='Universitet tomonidan tasdiqlangan hisob')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
