# Generated by Django 5.2.17 on 2026-09-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, help_text='Talaba ID (masalan: 2311195)', max_length=50, null=True),
        ),
    ]
