# Generated by Django 5.2.17 on 2026-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studentprofile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='japanese_exempt',
            field=models.BooleanField(default=True, help_text='Yapon tili darslaridan ozod qilinganligi'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='partner_university',
            field=models.CharField(blank=True, default='Tokyo Online University (TOU)', help_text='Hamkor universitet (TOU, SANNO, Niigata va h.k.)', max_length=150),
        ),
    ]
