services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: univer_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/venv
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-dev-key
      - ALLOWED_UNIVERSITY_DOMAINS=jdu.uz
      - GOOGLE_CLIENT_ID=
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: univer_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
