# Generated by Django 5.0.14 on 2026-09-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(db_index=True, default='2026_09', help_text="O'quv semestri (masalan: 2026_09 yoki 2026_04)", max_length=30)),
                ('day_index', models.IntegerField(choices=[(0, 'Dushanba (月)'), (1, 'Seshanba (火)'), (2, 'Chorshanba (水)'), (3, 'Payshanba (木)'), (4, 'Juma (金)'), (5, 'Shanba (土)'), (6, 'Yakshanba (日)')], db_index=True, default=0, help_text='Hafta kuni indeksi (0=Dushanba, 1=Seshanba...)')),
                ('day_name', models.CharField(default='Dushanba', help_text="Hafta kuni nomi o'zbek tilida (Dushanba, Seshanba...)", max_length=30)),
                ('period', models.IntegerField(default=1, help_text='Para raqami (1-para, 2-para... 1 dan 6 gacha)')),
                ('start_time', models.TimeField(help_text='Dars boshlanish vaqti (masalan: 09:00)')),
                ('end_time', models.TimeField(help_text='Dars tugash vaqti (masalan: 10:15)')),
                ('subject', models.CharField(db_index=True, help_text="Fan yoki mashg'ulot nomi", max_length=200)),
                ('teacher', models.CharField(blank=True, default='', help_text="O'qituvchi ismi (Erkaboy, Sonobe...)", max_length=150)),
                ('room', models.CharField(blank=True, default='', help_text='Xona raqami (masalan: 304, 203, Zoom)', max_length=50)),
                ('groups', models.JSONField(default=list, help_text="Tegishli guruhlar ro'yxati (masalan: ['23D', '23E'])")),
                ('target_partner', models.CharField(default='ALL', help_text='Hamkor OTM filtri (TOU, SANNO, ALL)', max_length=50)),
                ('is_japanese', models.BooleanField(default=False, help_text="Yapon tili darsimi (agar talaba ozod bo'lsa ko'rsatilmaydi)")),
                ('class_type', models.CharField(blank=True, default='lecture', help_text='Dars turi (lecture, seminar, interview, meeting)', max_length=50)),
                ('notes', models.TextField(blank=True, default='', help_text="Qo'shimcha izohlar (toq haftalar, o'quv qurollari va h.k.)")),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Oxirgi sinxronizatsiya vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
                'ordering': ['day_index', 'period', 'room'],
            },
        ),
    ]
