# Generated by Django 5.2.17 on 2026-09-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetableentry",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Dars tugash vaqti (avtomatik qo'yiladi)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="period",
            field=models.IntegerField(
                choices=[
                    (1, "1-para (09:00 - 10:15)"),
                    (2, "2-para (10:25 - 11:40)"),
                    (3, "3-para (11:50 - 13:05)"),
                    (4, "4-para (13:50 - 15:05)"),
                    (5, "5-para (15:15 - 16:30)"),
                    (6, "6-para (16:40 - 17:55)"),
                ],
                default=1,
                help_text="Para raqami (1 dan 6 gacha)",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="start_time",
            field=models.TimeField(
                blank=True,
                help_text="Dars boshlanish vaqti (avtomatik qo'yiladi)",
                null=True,
            ),
        ),
    ]
