# Generated by Django 5.2.17 on 2026-09-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_alter_timetableentry_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableentry",
            name="specific_date",
            field=models.DateField(
                blank=True,
                help_text="Aniq sana (agar faqat bir kunga tegishli bo'lsa, qaysi kunligi avtomatik olinadi)",
                null=True,
            ),
        ),
    ]
