# Generated by Django 5.2.17 on 2026-09-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0003_timetableentry_specific_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetableentry",
            name="day_index",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Dushanba (月)"),
                    (1, "Seshanba (火)"),
                    (2, "Chorshanba (水)"),
                    (3, "Payshanba (木)"),
                    (4, "Juma (金)"),
                    (5, "Shanba (土)"),
                    (6, "Yakshanba (日)"),
                ],
                db_index=True,
                help_text="Hafta kuni indeksi (0=Dushanba, 1=Seshanba...)",
                null=True,
            ),
        ),
    ]
