# Generated by Django 5.2.17 on 2026-09-19 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, db_index=True, help_text='Rasmiy talaba ID raqami (masalan: 2311194)', max_length=50, null=True, unique=True)),
                ('group', models.CharField(db_index=True, default='23D', help_text='Guruh (masalan: 23D, 24A)', max_length=50)),
                ('course', models.CharField(default='3', help_text='Bosqich / Kurs (masalan: 1, 2, 3, 4)', max_length=50)),
                ('direction', models.CharField(default='IT', help_text="Yo'nalish (IT, Axborot xavfsizligi va h.k.)", max_length=100)),
                ('partner_university', models.CharField(default='Tokyo Online University (TOU)', help_text='Hamkor universitet (TOU, SANNO, Okayama, Niigata)', max_length=150)),
                ('japanese_exempt', models.BooleanField(default=True, help_text="Yapon tili darslaridan ozod qilinganlik holati (JAPANESE varag'i asosida)")),
                ('avatar_url', models.TextField(blank=True, help_text='Profil rasmi havolasi', null=True)),
                ('phone', models.CharField(blank=True, help_text='Telefon raqami', max_length=30, null=True)),
                ('bio', models.TextField(blank=True, help_text="Qisqacha talaba ma'lumoti", null=True)),
                ('is_verified', models.BooleanField(default=False, help_text="Universitet rasmiy ro'yxatida tasdiqlangan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['student_id'],
            },
        ),
    ]
