# Generated by Django 5.0.14 on 2026-09-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='data_jdu_hash',
            field=models.CharField(blank=True, db_index=True, help_text='data.jdu.uz shaxsiy sahifa kodi (masalan: 2c7a6987)', max_length=50, null=True),
        ),
    ]
