# Generated by Django 5.0.14 on 2026-09-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_data_jdu_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='japanese_level',
            field=models.CharField(blank=True, default='N3', help_text='Yapon tili darajasi (masalan: N2, N3, N4, N5, N3D, N2A)', max_length=20, null=True),
        ),
    ]
