# Generated by Django 5.2.17 on 2026-09-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_studentprofile_japanese_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="fcm_token",
            field=models.CharField(
                blank=True,
                help_text="Firebase Cloud Messaging token for push notifications",
                max_length=255,
                null=True,
            ),
        ),
    ]
