class AppStrings {
  static const Map<String, Map<String, String>> _localized = {
    'uz': {
      'app_name': 'UNIVER SuperApp',
      'app_subtitle': 'Japan Digital University • Tokyo Online University',
      'login_title': 'Xush kelibsiz',
      'login_desc': 'Dars jadvalini ko\'rish uchun universitet hisobingizga kiring',
      'email_label': 'Universitet emaili',
      'email_hint': '2311194e@jdu.uz',
      'password_label': 'Parol',
      'login_btn': 'Tizimga Kirish',
      'email_empty': 'Email va parolni kiriting',
      'domain_error': 'Faqat rasmiy universitet emaili (@jdu.uz) orqali kirish mumkin!',
      'quick_test': 'TEZKOR SINOV TALABALARI',
      'next_class': 'KEYINGI DARS',
      'next_class_today': 'KEYINGI DARS (BUGUN)',
      'no_more_classes': 'Bugungi darslar tugadi',
      'no_more_classes_desc': 'Yaqin orada yangi darslar rejalashtirilmagan',
      'no_classes_day': 'Bu kunda darslar yo\'q',
      'no_classes_day_desc': 'Tanlangan kunga dars jadvali rejalashtirilmagan',
      'classes_suffix': 'ta',
      'period_suffix': '-para',
      'room_suffix': '-xona',
      'group': 'Guruh',
      'course': 'Kurs',
      'direction': 'Yo\'nalish',
      'partner_uni': 'Hamkor OTM',
      'student_id': 'Talaba ID',
      'japanese': 'Yapon tili darslari',
      'japanese_exempt': 'Ozod qilingan (Imtihondan o\'tgan)',
      'japanese_required': 'Qatnashishi majburiy',
      'verified_account': 'Rasmiy tasdiqlangan',
      'profile_title': 'Talaba Profili',
      'logout': 'Hisobdan Chiqish',
      'logout_confirm_title': 'Chiqishni xohlaysizmi?',
      'logout_confirm_desc': 'Hisobingizdan chiqmoqchimisiz?',
      'cancel': 'Bekor qilish',
      'retry': 'Qayta urinish',
      'error_occurred': 'Xatolik yuz berdi',
      'theme_light': 'Yorug\' rejim',
      'theme_dark': 'Qorong\'u rejim',
      'univ_instructor': 'Universitet o\'qituvchisi',
      'japanese_teacher': 'Yapon tili o\'qituvchisi',
      'assembly_hall': 'Faollar zali',
      'role_student': 'Talaba',
      'course_n': '{n}-kurs',
      'dir_it': 'Axborot texnologiyalari (IT)',
      'day_off': 'Dam olish',
      'upcoming': 'Yaqinda',
      // Days full
      'day_0': 'Dushanba',
      'day_1': 'Seshanba',
      'day_2': 'Chorshanba',
      'day_3': 'Payshanba',
      'day_4': 'Juma',
      'day_5': 'Shanba',
      'day_6': 'Yakshanba',
      // Days short
      'day_short_0': 'Du',
      'day_short_1': 'Se',
      'day_short_2': 'Chor',
      'day_short_3': 'Pay',
      'day_short_4': 'Jum',
      'day_short_5': 'Shan',
      'day_short_6': 'Yak',
      // Sidebar
      'nav_timetable': 'Dars Jadvali',
      'nav_academics': 'O\'zlashtirish',
      'nav_profile': 'Profil',
      // Academics
      'academics_title': 'O\'zlashtirish va Davomat',
      'gpa_title': 'GPA Ko\'rsatkich',
      'attendance_title': 'Davomat',
      'grades_title': 'Baholar',
      'credits_title': 'Kreditlar',
      'overall': 'Umumiy',
      'attended': 'Qatnashgan',
      'missed': 'Qoldirgan',
      'excused': 'Sababli',
      'can_miss': 'Qoldirishingiz mumkin',
      'classes': 'dars',
      'assignments': 'Topshiriqlar',
      'deadline': 'Muddati',
      'mark': 'Baho',
      'no_data': 'Ma\'lumot yo\'q',
      'enter_link_title': 'data.jdu.uz havolasini kiriting',
      'enter_link_desc': 'SMS orqali kelgan havolangizni kiriting yoki nusxalab joylashtiring',
      'enter_link_hint': 'https://data.jdu.uz/...',
      'paste_btn': 'Nusxadan joylashtirish',
      'save_btn': 'Saqlash',
      'link_saved': 'Havola muvaffaqiyatli saqlandi!',
      'link_error': 'Havola noto\'g\'ri. Qaytadan kiriting.',
      'loading_data': 'Ma\'lumotlar yuklanmoqda...',
      'safe': 'Xavfsiz',
      'warning': 'Diqqat',
      'danger': 'Xavfli',
      'excellent': 'A\'lo',
      'good': 'Yaxshi',
      'needs_work': 'Ishlash kerak',
      'failing': 'Yiqilish xavfi',
      'attendance_not_published': 'Universitet tomonidan davomat hali kiritilmagan',
      'attendance_pending_badge': 'Kiritilmagan',
      'change_avatar': 'Profil rasmini o\'zgartirish',
      'choose_from_gallery': 'Galereyadan tanlash',
      'preset_avatars': 'Universitet avatarlari',
      'remove_avatar': 'Rasmni o\'chirish',
      'avatar_updated': 'Profil rasmi yangilandi!',
      'monthly_timetable': 'Oylik dars jadvali',
      'no_classes_this_month': 'Bu oydagi darslar haqida ma\'lumot mavjud emas',
      'view_monthly_schedule': 'To\'liq oylik jadvalni ko\'rish yoki yuklab olish',
      'Kovorking': 'Kovorking',
      'Kovorking faoliyati': 'Kovorking faoliyati',
      'risk_danger': '{subj}: Davomat {pct}% — 80% dan past! Imtihonga kiritilmaslik xavfi mavjud!',
      'risk_warning_1': '{subj}: Yana 1 ta dars qoldirsangiz, davomat 80% dan tushib ketadi!',
      'risk_warning_n': '{subj}: Diqqat! Faqat {n} ta dars qoldirish mumkin.',
      'risk_safe': '{subj}: Davomatingiz yaxshi, lekin faqat {n} ta dars qoldirishingiz mumkin.',
      'overall_danger': 'UMUMIY DAVOMAT {pct}% — XAVFLI! 80% dan past!',
      'overall_warning': 'Umumiy davomat {pct}% — 80% chegarasiga yaqin!',
    },
    'en': {
      'app_name': 'UNIVER SuperApp',
      'app_subtitle': 'Japan Digital University • Tokyo Online University',
      'login_title': 'Welcome Back',
      'login_desc': 'Sign in with your university account to access your schedule',
      'email_label': 'University Email',
      'email_hint': '2311194e@jdu.uz',
      'password_label': 'Password',
      'login_btn': 'Sign In',
      'email_empty': 'Please enter email and password',
      'domain_error': 'Only official university emails (@jdu.uz) are allowed!',
      'quick_test': 'QUICK TEST STUDENTS',
      'next_class': 'NEXT CLASS',
      'next_class_today': 'NEXT CLASS (TODAY)',
      'no_more_classes': 'All classes completed',
      'no_more_classes_desc': 'No upcoming classes scheduled soon',
      'no_classes_day': 'No classes on this day',
      'no_classes_day_desc': 'No classes scheduled for the selected day',
      'classes_suffix': 'cls',
      'period_suffix': ' Period',
      'room_suffix': ' Room',
      'group': 'Group',
      'course': 'Year / Course',
      'direction': 'Major',
      'partner_uni': 'Partner University',
      'student_id': 'Student ID',
      'japanese': 'Japanese Classes',
      'japanese_exempt': 'Exempt (Exam Passed)',
      'japanese_required': 'Attendance Required',
      'verified_account': 'Officially Verified',
      'profile_title': 'Student Profile',
      'logout': 'Log Out',
      'logout_confirm_title': 'Log Out',
      'logout_confirm_desc': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'retry': 'Retry',
      'error_occurred': 'An error occurred',
      'theme_light': 'Light Mode',
      'theme_dark': 'Dark Mode',
      'univ_instructor': 'University Lecturer',
      'japanese_teacher': 'Japanese Instructor',
      'assembly_hall': 'Assembly Hall',
      'role_student': 'Student',
      'course_n': 'Year {n}',
      'dir_it': 'Information Technology (IT)',
      'day_off': 'Day Off',
      'upcoming': 'Upcoming',
      // Days full
      'day_0': 'Monday',
      'day_1': 'Tuesday',
      'day_2': 'Wednesday',
      'day_3': 'Thursday',
      'day_4': 'Friday',
      'day_5': 'Saturday',
      'day_6': 'Sunday',
      // Days short
      'day_short_0': 'Mon',
      'day_short_1': 'Tue',
      'day_short_2': 'Wed',
      'day_short_3': 'Thu',
      'day_short_4': 'Fri',
      'day_short_5': 'Sat',
      'day_short_6': 'Sun',
      // Sidebar
      'nav_timetable': 'Timetable',
      'nav_academics': 'Academics',
      'nav_profile': 'Profile',
      // Academics
      'academics_title': 'Academics & Attendance',
      'gpa_title': 'GPA Score',
      'attendance_title': 'Attendance',
      'grades_title': 'Grades',
      'credits_title': 'Credits',
      'overall': 'Overall',
      'attended': 'Attended',
      'missed': 'Missed',
      'excused': 'Excused',
      'can_miss': 'Can still miss',
      'classes': 'classes',
      'assignments': 'Assignments',
      'deadline': 'Deadline',
      'mark': 'Mark',
      'no_data': 'No data',
      'enter_link_title': 'Enter your data.jdu.uz link',
      'enter_link_desc': 'Paste the link sent to you via SMS from JDU',
      'enter_link_hint': 'https://data.jdu.uz/...',
      'paste_btn': 'Paste from clipboard',
      'save_btn': 'Save',
      'link_saved': 'Link saved successfully!',
      'link_error': 'Invalid link. Please try again.',
      'loading_data': 'Loading data...',
      'safe': 'Safe',
      'warning': 'Warning',
      'danger': 'Danger',
      'excellent': 'Excellent',
      'good': 'Good',
      'needs_work': 'Needs work',
      'failing': 'At risk',
      'attendance_not_published': 'Attendance records not yet published by university',
      'attendance_pending_badge': 'Pending',
      'change_avatar': 'Change Profile Photo',
      'choose_from_gallery': 'Choose from Gallery',
      'preset_avatars': 'Preset Avatars',
      'remove_avatar': 'Remove Photo',
      'avatar_updated': 'Profile photo updated!',
      'monthly_timetable': 'Monthly Timetable',
      'no_classes_this_month': 'No classes scheduled for this month',
      'view_monthly_schedule': 'View or download full monthly schedule',
      'Kovorking': 'Coworking',
      'Kovorking faoliyati': 'Coworking Activities',
      'risk_danger': '{subj}: Attendance {pct}% — below 80%! Exam ban risk!',
      'risk_warning_1': '{subj}: Missing 1 more class will drop attendance below 80%!',
      'risk_warning_n': '{subj}: Warning! You can only miss {n} more classes.',
      'risk_safe': '{subj}: Attendance is good, but you can only miss {n} more classes.',
      'overall_danger': 'OVERALL ATTENDANCE {pct}% — DANGER! Below 80%!',
      'overall_warning': 'Overall attendance {pct}% — Near the 80% limit!',
    },
    'ja': {
      'app_name': 'UNIVER SuperApp',
      'app_subtitle': '日本デジタル大学（JDU）・東京通信大学（TOU）',
      'login_title': 'おかえりなさい',
      'login_desc': '時間割を確認するには大学アカウントでログインしてください',
      'email_label': '大学メールアドレス',
      'email_hint': '2311194e@jdu.uz',
      'password_label': 'パスワード',
      'login_btn': 'ログイン',
      'email_empty': 'メールアドレスとパスワードを入力してください',
      'domain_error': '大学公式メール（@jdu.uz）のみログイン可能です！',
      'quick_test': 'クイックテスト学生',
      'next_class': '次の授業',
      'next_class_today': '次の授業（本日）',
      'no_more_classes': '本日の授業は終了しました',
      'no_more_classes_desc': '直近の予定された授業はありません',
      'no_classes_day': 'この日の授業はありません',
      'no_classes_day_desc': '選択した曜日に予定されている授業はありません',
      'classes_suffix': 'コマ',
      'period_suffix': '限',
      'room_suffix': '教室',
      'group': 'クラス',
      'course': '学年',
      'direction': '専攻',
      'partner_uni': '提携大学',
      'student_id': '学籍番号',
      'japanese': '日本語科目',
      'japanese_exempt': '免除（試験合格済み）',
      'japanese_required': '受講必須',
      'verified_account': '公式認証済み',
      'profile_title': '学生プロフィール',
      'logout': 'ログアウト',
      'logout_confirm_title': 'ログアウト確認',
      'logout_confirm_desc': '本当にログアウトしますか？',
      'cancel': 'キャンセル',
      'retry': '再試行',
      'error_occurred': 'エラーが発生しました',
      'theme_light': 'ライトモード',
      'theme_dark': 'ダークモード',
      'univ_instructor': '大学講師',
      'japanese_teacher': '日本語教員',
      'assembly_hall': '講堂',
      'role_student': '学生',
      'course_n': '{n}年生',
      'dir_it': '情報技術 (IT)',
      'day_off': '休講日',
      'upcoming': 'まもなく',
      // Days full
      'day_0': '月曜日',
      'day_1': '火曜日',
      'day_2': '水曜日',
      'day_3': '木曜日',
      'day_4': '金曜日',
      'day_5': '土曜日',
      'day_6': '日曜日',
      // Days short
      'day_short_0': '月',
      'day_short_1': '火',
      'day_short_2': '水',
      'day_short_3': '木',
      'day_short_4': '金',
      'day_short_5': '土',
      'day_short_6': '日',
      // Sidebar
      'nav_timetable': '時間割',
      'nav_academics': '成績',
      'nav_profile': 'プロフィール',
      // Academics
      'academics_title': '成績と出席',
      'gpa_title': 'GPA',
      'attendance_title': '出席率',
      'grades_title': '成績',
      'credits_title': '単位',
      'overall': '全体',
      'attended': '出席',
      'missed': '欠席',
      'excused': '公欠',
      'can_miss': '残り欠席可能',
      'classes': '回',
      'assignments': '課題',
      'deadline': '提出期限',
      'mark': '点数',
      'no_data': 'データなし',
      'enter_link_title': 'data.jdu.uzリンクを入力',
      'enter_link_desc': 'SMSで届いたリンクを貼り付けてください',
      'enter_link_hint': 'https://data.jdu.uz/...',
      'paste_btn': 'クリップボードから貼り付け',
      'save_btn': '保存',
      'link_saved': 'リンクが保存されました！',
      'link_error': '無効なリンクです。もう一度お試しください。',
      'loading_data': 'データ読み込み中...',
      'safe': '安全',
      'warning': '注意',
      'danger': '危険',
      'excellent': '優良',
      'good': '良好',
      'needs_work': '努力が必要',
      'failing': '単位落ち注意',
      'attendance_not_published': '大学側で出席データがまだ入力されていません',
      'attendance_pending_badge': '未入力',
      'change_avatar': 'プロフィール写真を変更',
      'choose_from_gallery': 'ギャラリーから選択',
      'preset_avatars': 'プリセットアバター',
      'remove_avatar': '写真を削除',
      'avatar_updated': 'プロフィール写真を更新しました',
      'monthly_timetable': '月間時間割',
      'no_classes_this_month': '今月の授業予定はありません',
      'view_monthly_schedule': '月間スケジュール全体を表示またはダウンロード',
      'Kovorking': 'コワーキング',
      'Kovorking faoliyati': 'コワーキング活動',
      'risk_danger': '{subj}: 出席率 {pct}% — 80%未満です！試験禁止の危険があります！',
      'risk_warning_1': '{subj}: もう1回欠席すると、出席率が80%を下回ります！',
      'risk_warning_n': '{subj}: 警告！あと {n} 回しか欠席できません。',
      'risk_safe': '{subj}: 出席率は良好ですが、あと {n} 回しか欠席できません。',
      'overall_danger': '全体出席率 {pct}% — 危険！80%未満です！',
      'overall_warning': '全体出席率 {pct}% — 80%の制限に近づいています！',
    },
    'ru': {
      'app_name': 'UNIVER SuperApp',
      'app_subtitle': 'Japan Digital University • Tokyo Online University',
      'login_title': 'Добро пожаловать',
      'login_desc': 'Войдите с университетским аккаунтом для просмотра расписания',
      'email_label': 'Университетский email',
      'email_hint': '2311194e@jdu.uz',
      'password_label': 'Пароль',
      'login_btn': 'Войти',
      'email_empty': 'Введите email и пароль',
      'domain_error': 'Разрешен вход только через университетский email (@jdu.uz)!',
      'quick_test': 'БЫСТРЫЙ ТЕСТОВЫЙ ВХОД',
      'next_class': 'СЛЕДУЮЩАЯ ПАРА',
      'next_class_today': 'СЛЕДУЮЩАЯ ПАРА (СЕГОДНЯ)',
      'no_more_classes': 'Занятия на сегодня завершены',
      'no_more_classes_desc': 'В ближайшее время занятий нет',
      'no_classes_day': 'В этот день занятий нет',
      'no_classes_day_desc': 'На выбранный день расписание отсутствует',
      'classes_suffix': 'пар',
      'period_suffix': '-пара',
      'room_suffix': '-ауд.',
      'group': 'Группа',
      'course': 'Курс',
      'direction': 'Направление',
      'partner_uni': 'Партнерский ВУЗ',
      'student_id': 'ID студента',
      'japanese': 'Японский язык',
      'japanese_exempt': 'Освобожден (Экзамен сдан)',
      'japanese_required': 'Обязательно к посещению',
      'verified_account': 'Официально подтвержден',
      'profile_title': 'Профиль студента',
      'logout': 'Выйти из аккаунта',
      'logout_confirm_title': 'Выход из аккаунта',
      'logout_confirm_desc': 'Вы уверены, что хотите выйти?',
      'cancel': 'Отмена',
      'retry': 'Повторить',
      'error_occurred': 'Произошла ошибка',
      'theme_light': 'Светлая тема',
      'theme_dark': 'Темная тема',
      'univ_instructor': 'Преподаватель университета',
      'japanese_teacher': 'Преподаватель японского',
      'assembly_hall': 'Актовый зал',
      'role_student': 'Студент',
      'course_n': '{n}-й курс',
      'dir_it': 'Информационные технологии (IT)',
      'day_off': 'Выходной',
      'upcoming': 'Скоро',
      // Days full
      'day_0': 'Понедельник',
      'day_1': 'Вторник',
      'day_2': 'Среда',
      'day_3': 'Четверг',
      'day_4': 'Пятница',
      'day_5': 'Суббота',
      'day_6': 'Воскресенье',
      // Days short
      'day_short_0': 'Пн',
      'day_short_1': 'Вт',
      'day_short_2': 'Ср',
      'day_short_3': 'Чт',
      'day_short_4': 'Пт',
      'day_short_5': 'Сб',
      'day_short_6': 'Вс',
      // Sidebar
      'nav_timetable': 'Расписание',
      'nav_academics': 'Успеваемость',
      'nav_profile': 'Профиль',
      // Academics
      'academics_title': 'Успеваемость и посещаемость',
      'gpa_title': 'Средний балл (GPA)',
      'attendance_title': 'Посещаемость',
      'grades_title': 'Оценки',
      'credits_title': 'Кредиты',
      'overall': 'Общий',
      'attended': 'Присутствовал',
      'missed': 'Пропустил',
      'excused': 'По уваж. причине',
      'can_miss': 'Можно пропустить',
      'classes': 'занятий',
      'assignments': 'Задания',
      'deadline': 'Срок сдачи',
      'mark': 'Оценка',
      'no_data': 'Нет данных',
      'enter_link_title': 'Введите ссылку data.jdu.uz',
      'enter_link_desc': 'Вставьте ссылку, полученную по SMS от JDU',
      'enter_link_hint': 'https://data.jdu.uz/...',
      'paste_btn': 'Вставить из буфера',
      'save_btn': 'Сохранить',
      'link_saved': 'Ссылка успешно сохранена!',
      'link_error': 'Неверная ссылка. Попробуйте ещё раз.',
      'loading_data': 'Загрузка данных...',
      'safe': 'Безопасно',
      'warning': 'Внимание',
      'danger': 'Опасно',
      'excellent': 'Отлично',
      'good': 'Хорошо',
      'needs_work': 'Нужна работа',
      'failing': 'Риск провала',
      'attendance_not_published': 'Посещаемость пока не внесена университетом',
      'attendance_pending_badge': 'Не внесено',
      'change_avatar': 'Изменить фото профиля',
      'choose_from_gallery': 'Выбрать из галереи',
      'preset_avatars': 'Готовые аватары',
      'remove_avatar': 'Удалить фото',
      'avatar_updated': 'Фото профиля обновлено!',
      'monthly_timetable': 'Месячное расписание',
      'no_classes_this_month': 'Нет информации о занятиях в этом месяце',
      'view_monthly_schedule': 'Посмотреть или скачать расписание на месяц',
      'Kovorking': 'Коворкинг',
      'Kovorking faoliyati': 'Коворкинг',
      'risk_danger': '{subj}: Посещаемость {pct}% — ниже 80%! Риск недопуска к экзамену!',
      'risk_warning_1': '{subj}: Еще 1 пропуск, и посещаемость упадет ниже 80%!',
      'risk_warning_n': '{subj}: Внимание! Можно пропустить только {n} занятия.',
      'risk_safe': '{subj}: Посещаемость хорошая, но можно пропустить только {n} занятия.',
      'overall_danger': 'ОБЩАЯ ПОСЕЩАЕМОСТЬ {pct}% — ОПАСНО! Ниже 80%!',
      'overall_warning': 'Общая посещаемость {pct}% — Близка к пределу в 80%!',
    },
  };

  static String get(String key, String langCode) {
    final lang = _localized[langCode] ?? _localized['uz']!;
    return lang[key] ?? _localized['uz']![key] ?? key;
  }
}
